// Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand.
export const tokens = {
  "color": {
    "night": {
      "600": {
        "value": "#3A3D44",
        "cssVar": "--au-night-600"
      },
      "700": {
        "value": "#2A2D33",
        "cssVar": "--au-night-700"
      },
      "750": {
        "value": "#1E2024",
        "cssVar": "--au-night-750"
      },
      "800": {
        "value": "#181A1E",
        "cssVar": "--au-night-800"
      },
      "850": {
        "value": "#131418",
        "cssVar": "--au-night-850"
      },
      "900": {
        "value": "#0E0F11",
        "cssVar": "--au-night-900"
      },
      "950": {
        "value": "#08090A",
        "cssVar": "--au-night-950"
      }
    },
    "stone": {
      "50": {
        "value": "#EDEBE5",
        "cssVar": "--au-stone-50"
      },
      "200": {
        "value": "#C9C6BE",
        "cssVar": "--au-stone-200"
      },
      "300": {
        "value": "#9C9A93",
        "cssVar": "--au-stone-300"
      },
      "400": {
        "value": "#8B8981",
        "cssVar": "--au-stone-400"
      },
      "500": {
        "value": "#86847D",
        "cssVar": "--au-stone-500"
      },
      "600": {
        "value": "#5C5B56",
        "cssVar": "--au-stone-600"
      },
      "700": {
        "value": "#4A4945",
        "cssVar": "--au-stone-700"
      }
    },
    "aurora": {
      "mint": {
        "value": "#7FD9C0",
        "cssVar": "--au-aurora-mint"
      },
      "violet": {
        "value": "#A78BE0",
        "cssVar": "--au-aurora-violet"
      }
    },
    "ember": {
      "400": {
        "value": "#E58F80",
        "cssVar": "--au-ember-400"
      }
    },
    "bg": {
      "ground": {
        "value": "#08090A",
        "cssVar": "--au-bg-ground"
      },
      "raised": {
        "value": "#0E0F11",
        "cssVar": "--au-bg-raised"
      },
      "raised-hover": {
        "value": "#131418",
        "cssVar": "--au-bg-raised-hover"
      },
      "sunken": {
        "value": "#181A1E",
        "cssVar": "--au-bg-sunken"
      },
      "inverse": {
        "value": "#EDEBE5",
        "cssVar": "--au-bg-inverse"
      },
      "inverse-hover": {
        "value": "#C9C6BE",
        "cssVar": "--au-bg-inverse-hover"
      }
    },
    "border": {
      "hairline": {
        "value": "#1E2024",
        "cssVar": "--au-border-hairline"
      },
      "strong": {
        "value": "#2A2D33",
        "cssVar": "--au-border-strong"
      },
      "inverse": {
        "value": "#EDEBE5",
        "cssVar": "--au-border-inverse"
      }
    },
    "text": {
      "primary": {
        "value": "#EDEBE5",
        "cssVar": "--au-text-primary"
      },
      "secondary": {
        "value": "#9C9A93",
        "cssVar": "--au-text-secondary"
      },
      "tertiary": {
        "value": "#8B8981",
        "cssVar": "--au-text-tertiary"
      },
      "label": {
        "value": "#86847D",
        "cssVar": "--au-text-label"
      },
      "faint": {
        "value": "#5C5B56",
        "cssVar": "--au-text-faint"
      },
      "disabled": {
        "value": "#4A4945",
        "cssVar": "--au-text-disabled"
      },
      "inverse": {
        "value": "#08090A",
        "cssVar": "--au-text-inverse"
      },
      "critical": {
        "value": "#E58F80",
        "cssVar": "--au-text-critical"
      }
    },
    "light": {
      "lo": {
        "value": "#7FD9C0",
        "cssVar": "--au-light-lo"
      },
      "hi": {
        "value": "#A78BE0",
        "cssVar": "--au-light-hi"
      },
      "focus": {
        "value": "#7FD9C0",
        "cssVar": "--au-light-focus"
      }
    }
  },
  "font": {
    "family": {
      "serif": {
        "value": "'Newsreader Variable', Newsreader, 'Iowan Old Style', Charter, Georgia, serif",
        "cssVar": "--au-font-serif"
      },
      "sans": {
        "value": "'Nunito Sans Variable', 'Nunito Sans', 'Avenir Next', 'Segoe UI', system-ui, sans-serif",
        "cssVar": "--au-font-sans"
      },
      "mono": {
        "value": "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, Menlo, monospace",
        "cssVar": "--au-font-mono"
      }
    },
    "weight": {
      "regular": {
        "value": "400",
        "cssVar": "--au-weight-regular"
      },
      "medium": {
        "value": "500",
        "cssVar": "--au-weight-medium"
      },
      "semibold": {
        "value": "600",
        "cssVar": "--au-weight-semibold"
      }
    }
  },
  "space": {
    "0": {
      "value": "0px",
      "cssVar": "--au-space-0"
    },
    "1": {
      "value": "4px",
      "cssVar": "--au-space-1"
    },
    "2": {
      "value": "8px",
      "cssVar": "--au-space-2"
    },
    "3": {
      "value": "12px",
      "cssVar": "--au-space-3"
    },
    "4": {
      "value": "16px",
      "cssVar": "--au-space-4"
    },
    "5": {
      "value": "20px",
      "cssVar": "--au-space-5"
    },
    "6": {
      "value": "24px",
      "cssVar": "--au-space-6"
    },
    "8": {
      "value": "32px",
      "cssVar": "--au-space-8"
    },
    "10": {
      "value": "40px",
      "cssVar": "--au-space-10"
    },
    "12": {
      "value": "48px",
      "cssVar": "--au-space-12"
    },
    "16": {
      "value": "64px",
      "cssVar": "--au-space-16"
    },
    "20": {
      "value": "80px",
      "cssVar": "--au-space-20"
    },
    "24": {
      "value": "96px",
      "cssVar": "--au-space-24"
    },
    "32": {
      "value": "128px",
      "cssVar": "--au-space-32"
    },
    "px": {
      "value": "1px",
      "cssVar": "--au-space-px"
    },
    "0.5": {
      "value": "2px",
      "cssVar": "--au-space-0_5"
    }
  },
  "radius": {
    "none": {
      "value": "0px",
      "cssVar": "--au-radius-none"
    },
    "sm": {
      "value": "4px",
      "cssVar": "--au-radius-sm"
    },
    "md": {
      "value": "6px",
      "cssVar": "--au-radius-md"
    },
    "lg": {
      "value": "12px",
      "cssVar": "--au-radius-lg"
    },
    "device": {
      "value": "38px",
      "cssVar": "--au-radius-device"
    },
    "pill": {
      "value": "999px",
      "cssVar": "--au-radius-pill"
    }
  },
  "border": {
    "hairline": {
      "value": "1px",
      "cssVar": "--au-border-hairline"
    }
  },
  "easing": {
    "glide": {
      "value": "cubic-bezier(0.32, 0.72, 0, 1)",
      "cssVar": "--au-ease-glide"
    },
    "soft": {
      "value": "cubic-bezier(0.4, 0, 0.2, 1)",
      "cssVar": "--au-ease-soft"
    },
    "out": {
      "value": "cubic-bezier(0.25, 1, 0.5, 1)",
      "cssVar": "--au-ease-out"
    },
    "linear": {
      "value": "cubic-bezier(0, 0, 1, 1)",
      "cssVar": "--au-ease-linear"
    }
  },
  "duration": {
    "instant": {
      "value": "120ms",
      "cssVar": "--au-dur-instant"
    },
    "quick": {
      "value": "220ms",
      "cssVar": "--au-dur-quick"
    },
    "base": {
      "value": "340ms",
      "cssVar": "--au-dur-base"
    },
    "moderate": {
      "value": "460ms",
      "cssVar": "--au-dur-moderate"
    },
    "glide": {
      "value": "600ms",
      "cssVar": "--au-dur-glide"
    },
    "slow": {
      "value": "900ms",
      "cssVar": "--au-dur-slow"
    },
    "reveal": {
      "value": "1400ms",
      "cssVar": "--au-dur-reveal"
    },
    "hold": {
      "value": "840ms",
      "cssVar": "--au-dur-hold"
    },
    "drift": {
      "value": "12000ms",
      "cssVar": "--au-dur-drift"
    }
  },
  "type": {
    "display": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "56px",
      "lineHeight": 1.08,
      "letterSpacing": "-0.02em"
    },
    "headline": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "40px",
      "lineHeight": 1.15,
      "letterSpacing": "-0.014em"
    },
    "title-l": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "28px",
      "lineHeight": 1.25,
      "letterSpacing": "-0.01em"
    },
    "title": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "24px",
      "lineHeight": 1.33,
      "letterSpacing": "-0.008em"
    },
    "title-s": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "20px",
      "lineHeight": 1.3,
      "letterSpacing": "-0.006em"
    },
    "voice": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "18px",
      "lineHeight": 1.5,
      "letterSpacing": "0em"
    },
    "voice-s": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "14px",
      "lineHeight": 1.55,
      "letterSpacing": "0em"
    },
    "body-l": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "17px",
      "lineHeight": 1.65,
      "letterSpacing": "0em"
    },
    "body": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "15px",
      "lineHeight": 1.65,
      "letterSpacing": "0em"
    },
    "body-s": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "13px",
      "lineHeight": 1.5,
      "letterSpacing": "0em"
    },
    "caption": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "12px",
      "lineHeight": 1.45,
      "letterSpacing": "0em"
    },
    "figure": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 600,
      "fontSize": "11px",
      "lineHeight": 1.4,
      "letterSpacing": "0.06em"
    },
    "label": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 600,
      "fontSize": "10px",
      "lineHeight": 1.4,
      "letterSpacing": "0.2em"
    }
  },
  "motion": {
    "move": {
      "value": "600ms cubic-bezier(0.32, 0.72, 0, 1)",
      "cssVar": "--au-motion-move"
    },
    "fade": {
      "value": "340ms cubic-bezier(0.4, 0, 0.2, 1)",
      "cssVar": "--au-motion-fade"
    },
    "enter": {
      "value": "900ms cubic-bezier(0.25, 1, 0.5, 1)",
      "cssVar": "--au-motion-enter"
    },
    "morph": {
      "value": "660ms cubic-bezier(0.32, 0.72, 0, 1)",
      "cssVar": "--au-motion-morph"
    }
  }
} as const;

export type Tokens = typeof tokens;

/** Every token as a flat list, for docs tables. */
export const tokenList = [
  {
    "path": "color.night.600",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-600",
    "value": "#3A3D44",
    "alias": null,
    "description": "Scrollbars and inactive handles."
  },
  {
    "path": "color.night.700",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-700",
    "value": "#2A2D33",
    "alias": null,
    "description": "Strong hairline, hover borders."
  },
  {
    "path": "color.night.750",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-750",
    "value": "#1E2024",
    "alias": null,
    "description": "Hairline."
  },
  {
    "path": "color.night.800",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-800",
    "value": "#181A1E",
    "alias": null,
    "description": "Third raise: docs panels and code."
  },
  {
    "path": "color.night.850",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-850",
    "value": "#131418",
    "alias": null,
    "description": "Second raise: hover and pressed surfaces."
  },
  {
    "path": "color.night.900",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-900",
    "value": "#0E0F11",
    "alias": null,
    "description": "First raise: cards, controls at rest."
  },
  {
    "path": "color.night.950",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-night-950",
    "value": "#08090A",
    "alias": null,
    "description": "The ground. Every Aurora surface starts here."
  },
  {
    "path": "color.stone.50",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-50",
    "value": "#EDEBE5",
    "alias": null,
    "description": "Bone. Primary ink, warm rather than white."
  },
  {
    "path": "color.stone.200",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-200",
    "value": "#C9C6BE",
    "alias": null,
    "description": null
  },
  {
    "path": "color.stone.300",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-300",
    "value": "#9C9A93",
    "alias": null,
    "description": null
  },
  {
    "path": "color.stone.400",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-400",
    "value": "#8B8981",
    "alias": null,
    "description": null
  },
  {
    "path": "color.stone.500",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-500",
    "value": "#86847D",
    "alias": null,
    "description": "Retuned from the concept's #5C5B56 so labels pass WCAG AA on every surface."
  },
  {
    "path": "color.stone.600",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-600",
    "value": "#5C5B56",
    "alias": null,
    "description": null
  },
  {
    "path": "color.stone.700",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-stone-700",
    "value": "#4A4945",
    "alias": null,
    "description": null
  },
  {
    "path": "color.aurora.mint",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-aurora-mint",
    "value": "#7FD9C0",
    "alias": null,
    "description": "Low aurora. Where light starts."
  },
  {
    "path": "color.aurora.violet",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-aurora-violet",
    "value": "#A78BE0",
    "alias": null,
    "description": "High aurora. Where light ends."
  },
  {
    "path": "color.ember.400",
    "layer": "primitive",
    "type": "color",
    "cssVar": "--au-ember-400",
    "value": "#E58F80",
    "alias": null,
    "description": "The one warm signal. Destructive and error only."
  },
  {
    "path": "font.family.serif",
    "layer": "primitive",
    "type": "fontFamily",
    "cssVar": "--au-font-serif",
    "value": "'Newsreader Variable', Newsreader, 'Iowan Old Style', Charter, Georgia, serif",
    "alias": null,
    "description": null
  },
  {
    "path": "font.family.sans",
    "layer": "primitive",
    "type": "fontFamily",
    "cssVar": "--au-font-sans",
    "value": "'Nunito Sans Variable', 'Nunito Sans', 'Avenir Next', 'Segoe UI', system-ui, sans-serif",
    "alias": null,
    "description": null
  },
  {
    "path": "font.family.mono",
    "layer": "primitive",
    "type": "fontFamily",
    "cssVar": "--au-font-mono",
    "value": "'JetBrains Mono Variable', 'JetBrains Mono', ui-monospace, Menlo, monospace",
    "alias": null,
    "description": null
  },
  {
    "path": "font.weight.regular",
    "layer": "primitive",
    "type": "fontWeight",
    "cssVar": "--au-weight-regular",
    "value": "400",
    "alias": null,
    "description": null
  },
  {
    "path": "font.weight.medium",
    "layer": "primitive",
    "type": "fontWeight",
    "cssVar": "--au-weight-medium",
    "value": "500",
    "alias": null,
    "description": null
  },
  {
    "path": "font.weight.semibold",
    "layer": "primitive",
    "type": "fontWeight",
    "cssVar": "--au-weight-semibold",
    "value": "600",
    "alias": null,
    "description": null
  },
  {
    "path": "space.0",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-0",
    "value": "0px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.1",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-1",
    "value": "4px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.2",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-2",
    "value": "8px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.3",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-3",
    "value": "12px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.4",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-4",
    "value": "16px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.5",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-5",
    "value": "20px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.6",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-6",
    "value": "24px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.8",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-8",
    "value": "32px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.10",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-10",
    "value": "40px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.12",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-12",
    "value": "48px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.16",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-16",
    "value": "64px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.20",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-20",
    "value": "80px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.24",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-24",
    "value": "96px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.32",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-32",
    "value": "128px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.px",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-px",
    "value": "1px",
    "alias": null,
    "description": null
  },
  {
    "path": "space.0.5",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-space-0_5",
    "value": "2px",
    "alias": null,
    "description": null
  },
  {
    "path": "radius.none",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-none",
    "value": "0px",
    "alias": null,
    "description": null
  },
  {
    "path": "radius.sm",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-sm",
    "value": "4px",
    "alias": null,
    "description": "Controls: buttons, inputs."
  },
  {
    "path": "radius.md",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-md",
    "value": "6px",
    "alias": null,
    "description": "Containers: cards, panels."
  },
  {
    "path": "radius.lg",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-lg",
    "value": "12px",
    "alias": null,
    "description": "Stages and large media."
  },
  {
    "path": "radius.device",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-device",
    "value": "38px",
    "alias": null,
    "description": "Device frames only."
  },
  {
    "path": "radius.pill",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-radius-pill",
    "value": "999px",
    "alias": null,
    "description": "The ask bar and nothing else."
  },
  {
    "path": "border.hairline",
    "layer": "primitive",
    "type": "dimension",
    "cssVar": "--au-border-hairline",
    "value": "1px",
    "alias": null,
    "description": null
  },
  {
    "path": "easing.glide",
    "layer": "primitive",
    "type": "cubicBezier",
    "cssVar": "--au-ease-glide",
    "value": "cubic-bezier(0.32, 0.72, 0, 1)",
    "alias": null,
    "description": "Decelerates into place. Anything that moves or changes size."
  },
  {
    "path": "easing.soft",
    "layer": "primitive",
    "type": "cubicBezier",
    "cssVar": "--au-ease-soft",
    "value": "cubic-bezier(0.4, 0, 0.2, 1)",
    "alias": null,
    "description": "Symmetric and quiet. Colour, opacity, borders."
  },
  {
    "path": "easing.out",
    "layer": "primitive",
    "type": "cubicBezier",
    "cssVar": "--au-ease-out",
    "value": "cubic-bezier(0.25, 1, 0.5, 1)",
    "alias": null,
    "description": "A long, gentle arrival. Entrances and reveals."
  },
  {
    "path": "easing.linear",
    "layer": "primitive",
    "type": "cubicBezier",
    "cssVar": "--au-ease-linear",
    "value": "cubic-bezier(0, 0, 1, 1)",
    "alias": null,
    "description": "Time itself. Only for progress that tracks a held gesture."
  },
  {
    "path": "duration.instant",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-instant",
    "value": "120ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.quick",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-quick",
    "value": "220ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.base",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-base",
    "value": "340ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.moderate",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-moderate",
    "value": "460ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.glide",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-glide",
    "value": "600ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.slow",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-slow",
    "value": "900ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.reveal",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-reveal",
    "value": "1400ms",
    "alias": null,
    "description": null
  },
  {
    "path": "duration.hold",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-hold",
    "value": "840ms",
    "alias": null,
    "description": "How long a hold to confirm takes. A safeguard, not decoration."
  },
  {
    "path": "duration.drift",
    "layer": "primitive",
    "type": "duration",
    "cssVar": "--au-dur-drift",
    "value": "12000ms",
    "alias": null,
    "description": "One slow cycle of ambient light."
  },
  {
    "path": "color.bg.ground",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-ground",
    "value": "#08090A",
    "alias": "color.night.950",
    "description": "Page background."
  },
  {
    "path": "color.bg.raised",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-raised",
    "value": "#0E0F11",
    "alias": "color.night.900",
    "description": "Cards and controls at rest."
  },
  {
    "path": "color.bg.raised-hover",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-raised-hover",
    "value": "#131418",
    "alias": "color.night.850",
    "description": "Raised surfaces under a pointer."
  },
  {
    "path": "color.bg.sunken",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-sunken",
    "value": "#181A1E",
    "alias": "color.night.800",
    "description": "Code, wells, docs panels."
  },
  {
    "path": "color.bg.inverse",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-inverse",
    "value": "#EDEBE5",
    "alias": "color.stone.50",
    "description": "Fills that have been committed, like a held button."
  },
  {
    "path": "color.bg.inverse-hover",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-bg-inverse-hover",
    "value": "#C9C6BE",
    "alias": "color.stone.200",
    "description": "Inverse fills under a pointer."
  },
  {
    "path": "color.border.hairline",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-border-hairline",
    "value": "#1E2024",
    "alias": "color.night.750",
    "description": "Default 1px structure."
  },
  {
    "path": "color.border.strong",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-border-strong",
    "value": "#2A2D33",
    "alias": "color.night.700",
    "description": "Hover, and controls that need a visible edge."
  },
  {
    "path": "color.border.inverse",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-border-inverse",
    "value": "#EDEBE5",
    "alias": "color.stone.50",
    "description": null
  },
  {
    "path": "color.text.primary",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-primary",
    "value": "#EDEBE5",
    "alias": "color.stone.50",
    "description": "What Aurora says. 16.7:1 on ground."
  },
  {
    "path": "color.text.secondary",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-secondary",
    "value": "#9C9A93",
    "alias": "color.stone.300",
    "description": "Supporting prose. 7.1:1."
  },
  {
    "path": "color.text.tertiary",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-tertiary",
    "value": "#8B8981",
    "alias": "color.stone.400",
    "description": "Details and metadata. 5.7:1."
  },
  {
    "path": "color.text.label",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-label",
    "value": "#86847D",
    "alias": "color.stone.500",
    "description": "Uppercase labels. 5.3:1."
  },
  {
    "path": "color.text.faint",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-faint",
    "value": "#5C5B56",
    "alias": "color.stone.600",
    "description": "Past or inactive content. Decorative, never the only carrier of meaning."
  },
  {
    "path": "color.text.disabled",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-disabled",
    "value": "#4A4945",
    "alias": "color.stone.700",
    "description": null
  },
  {
    "path": "color.text.inverse",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-inverse",
    "value": "#08090A",
    "alias": "color.night.950",
    "description": null
  },
  {
    "path": "color.text.critical",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-text-critical",
    "value": "#E58F80",
    "alias": "color.ember.400",
    "description": null
  },
  {
    "path": "color.light.lo",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-light-lo",
    "value": "#7FD9C0",
    "alias": "color.aurora.mint",
    "description": "Start of the aurora."
  },
  {
    "path": "color.light.hi",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-light-hi",
    "value": "#A78BE0",
    "alias": "color.aurora.violet",
    "description": "End of the aurora."
  },
  {
    "path": "color.light.focus",
    "layer": "semantic",
    "type": "color",
    "cssVar": "--au-light-focus",
    "value": "#7FD9C0",
    "alias": "color.aurora.mint",
    "description": "Focus rings and selection."
  },
  {
    "path": "type.display",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-display",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "56px",
      "lineHeight": 1.08,
      "letterSpacing": "-0.02em"
    },
    "alias": null,
    "description": "One per page, at most. The thesis."
  },
  {
    "path": "type.headline",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-headline",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "40px",
      "lineHeight": 1.15,
      "letterSpacing": "-0.014em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.title-l",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-title-l",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "28px",
      "lineHeight": 1.25,
      "letterSpacing": "-0.01em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.title",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-title",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "24px",
      "lineHeight": 1.33,
      "letterSpacing": "-0.008em"
    },
    "alias": null,
    "description": "Screen greetings. What Aurora says first."
  },
  {
    "path": "type.title-s",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-title-s",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "20px",
      "lineHeight": 1.3,
      "letterSpacing": "-0.006em"
    },
    "alias": null,
    "description": "The thing being proposed."
  },
  {
    "path": "type.voice",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-voice",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "18px",
      "lineHeight": 1.5,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": "Quotes and held lines."
  },
  {
    "path": "type.voice-s",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-voice-s",
    "value": {
      "fontFamily": [
        "Newsreader Variable",
        "Newsreader",
        "Iowan Old Style",
        "Charter",
        "Georgia",
        "serif"
      ],
      "fontWeight": 400,
      "fontSize": "14px",
      "lineHeight": 1.55,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": "The reason. Always serif, always first."
  },
  {
    "path": "type.body-l",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-body-l",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "17px",
      "lineHeight": 1.65,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.body",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-body",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "15px",
      "lineHeight": 1.65,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.body-s",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-body-s",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "13px",
      "lineHeight": 1.5,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.caption",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-caption",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 400,
      "fontSize": "12px",
      "lineHeight": 1.45,
      "letterSpacing": "0em"
    },
    "alias": null,
    "description": null
  },
  {
    "path": "type.figure",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-figure",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 600,
      "fontSize": "11px",
      "lineHeight": 1.4,
      "letterSpacing": "0.06em"
    },
    "alias": null,
    "description": "Times and numbers. Tabular, lining, set with points: 09.30."
  },
  {
    "path": "type.label",
    "layer": "semantic",
    "type": "typography",
    "cssVar": ".au-type-label",
    "value": {
      "fontFamily": [
        "Nunito Sans Variable",
        "Nunito Sans",
        "Avenir Next",
        "Segoe UI",
        "system-ui",
        "sans-serif"
      ],
      "fontWeight": 600,
      "fontSize": "10px",
      "lineHeight": 1.4,
      "letterSpacing": "0.2em"
    },
    "alias": null,
    "description": "Uppercase metadata. Trim the trailing tracking on right-aligned runs."
  },
  {
    "path": "motion.move",
    "layer": "semantic",
    "type": "transition",
    "cssVar": "--au-motion-move",
    "value": "600ms cubic-bezier(0.32, 0.72, 0, 1)",
    "alias": null,
    "description": "Position and size."
  },
  {
    "path": "motion.fade",
    "layer": "semantic",
    "type": "transition",
    "cssVar": "--au-motion-fade",
    "value": "340ms cubic-bezier(0.4, 0, 0.2, 1)",
    "alias": null,
    "description": "Colour and opacity."
  },
  {
    "path": "motion.enter",
    "layer": "semantic",
    "type": "transition",
    "cssVar": "--au-motion-enter",
    "value": "900ms cubic-bezier(0.25, 1, 0.5, 1)",
    "alias": null,
    "description": "Content arriving."
  },
  {
    "path": "motion.morph",
    "layer": "semantic",
    "type": "transition",
    "cssVar": "--au-motion-morph",
    "value": "660ms cubic-bezier(0.32, 0.72, 0, 1)",
    "alias": null,
    "description": "A box changing into another box."
  }
] as const;
